import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext();
const page = await context.newPage();
await page.goto('http://localhost:5174', { waitUntil: 'networkidle' });
await page.waitForSelector('.gis-layer-control button[aria-label="Open layer manager"]', { timeout: 10000 });
await page.click('.gis-layer-control button[aria-label="Open layer manager"]');
await page.waitForTimeout(1000);
await page.screenshot({ path: 'layer-panel.png', fullPage: true });
console.log('Screenshot saved to layer-panel.png');
await browser.close();