export const EDGE_TYPES = {
  POWER_LINE: "POWER_LINE",
  FIBER_OPTIC: "FIBER_OPTIC",
  ROAD_ACCESS: "ROAD_ACCESS",
  WATER_PIPELINE: "WATER_PIPELINE",
  EMERGENCY_ROUTE: "EMERGENCY_ROUTE",
  MEDICAL_SERVICE: "MEDICAL_SERVICE",
};

export const DEPENDENCY_STRATEGY = {
  NEAREST: "NEAREST",
  ONE_TO_MANY: "ONE_TO_MANY",
  TARGET_CENTRIC: "TARGET_CENTRIC",
};
